# Generated by Django 5.1.1 on 2024-09-23 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=16)),
                ('age', models.IntegerField()),
                ('balance', models.DecimalField(decimal_places=2, max_digits=1000000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10000)),
                ('size', models.DecimalField(decimal_places=3, max_digits=1000)),
                ('description', models.TextField()),
                ('age_limited', models.BooleanField(default=False)),
                ('User', models.ManyToManyField(related_name='games', to='app.user')),
            ],
        ),
    ]
