# Generated by Django 5.1.1 on 2024-09-23 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='image',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
