# Generated by Django 5.1.1 on 2024-09-29 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_game_user_remove_game_age_limited_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('reviews', models.TextField()),
                ('image', models.ImageField(upload_to='static/img')),
            ],
        ),
    ]
