# Generated by Django 5.1.1 on 2024-09-29 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
