"""Initital migration

Revision ID: 623e31c8e7fd
Revises: e213bc8d9526
Create Date: 2024-09-30 02:57:14.103847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '623e31c8e7fd'
down_revision: Union[str, None] = 'e213bc8d9526'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('reviews', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('app_game', 'cost',
               existing_type=sa.DECIMAL(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('app_game', 'size',
               existing_type=sa.DECIMAL(),
               type_=sa.Integer(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('app_game', 'size',
               existing_type=sa.Integer(),
               type_=sa.DECIMAL(),
               existing_nullable=True)
    op.alter_column('app_game', 'cost',
               existing_type=sa.Integer(),
               type_=sa.DECIMAL(),
               existing_nullable=True)
    op.drop_table('app_post')
    # ### end Alembic commands ###
